### ISSUE TITLE
Project overview?

### ISSUE THREAD

**Issue by mkst** [timestored/jq#2]
It would be useful to have an overview of the project, e.g:

Features list - showing what has been implemented (e.g. none, partial, full), this could/should be broken down into the various categories, monads, diads, adverbs, bang functions, table operations, disk operations, etc

Milestones - what are the areas of focus? What would version "1.0" look like?

Bugs - How do you want bugs being reported? I've stumbled across a handful after playing around for a few minutes, but I don't think there is much value in raising bugs against missing functionality (unless it's explicitly called out as being complete)

Tests - are there any tests? Is there value in writing a bunch of tests for each piece of functionality (even if they would fail?)

K vs Q - early implementations would implement e.g. `sum` as "+/", but now it's a built-in, are you planning on building out functions in Java, or via K operations? Are you expecting people to provide their own .q.k file, or is there a plan for this to be written from scratch, clean-room style?

**Comment by ryanhamilton** [comment]
Added: https://github.com/timestored/jq/wiki
